name: Build Android APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build APK with Kivy Buildozer Action
      uses: kivy/buildozer-action@master
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Jarvis-Android-APK
        path: bin/*.apk
